### ISSUE TITLE
issueベースの開発機能　レビュー依頼

### ISSUE THREAD

**Issue by norikawasonoka** [norikawasonoka/sotuu#7]
実装予定の機能

- [ ] 会員登録
- [ ] ログイン
- [ ] パスワード変更機能
- [ ] 診断機能
- [ ] 診断結果機能
- [ ] 診断結果のお気に入り機能
- [ ] 診断結果のお気に入り機能の登録と削除
- [ ] お箏の道具
- [ ] お箏の演奏技術
- [ ] お問い合わせフォーム
- [ ] プライバシーポリシー、利用機能
- [ ] yutubuから音楽を取り込む機能（API yutubudata）
　
必要なページ

- [ ] トップページ
- [ ] 会員登録ページ
- [ ] ログインページ
- [ ] パスワードリセットページ
- [ ] 診断ページ
- [ ] 診断結果ページ
- [ ] お気に入りページ
- [ ] お箏の道具ページ
- [ ] お箏の演奏技術ページ
- [ ] お問い合わせページ
- [ ] プライバシーポリシー、利用機能ページ

**Comment by beppumasaki** [comment]
作成したissueをProjectsに紐づけて、エントリーポイントを設定してください！
https://school.runteq.jp/v3/curriculums/application_development/chapters/11

**Comment by norikawasonoka** [comment]
https://github.com/users/norikawasonoka/projects/4
プロジェクトのURLです。

**Comment by kenchasonakai** [comment]
LGTMです！
